export const MOVIE = {
    events: [
      {
        adult: false,
        backdrop_path: "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
        genre_ids: [18,878],
        id: 419704,
        original_language: "en",
        original_title: "Ad Astra",
        overview: "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
        popularity: 506.482,
        poster_path: "/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg",
        release_date: "2019-09-17",
        title: "Ad Astra",
        video: false,
        vote_average: 6,
        vote_count: 2998,
      },
      {
        adult: false,
        backdrop_path: "/upUy2QhMZEmtypPW3PdieKLAHxh.jpg",
        genre_ids: [28,80,53],
        id: 38700,
        original_language: "en",
        original_title: "Bad Boys for Life",
        overview: "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
        popularity: 263.273,
        poster_path: "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
        release_date: "2020-01-15",
        title: "Bad Boys for Life",
        video: false,
        vote_average: 7.2,
        vote_count: 2990,
      },
      {
        adult: false,
        backdrop_path: "/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg",
        genre_ids: [12, 16, 35, 14, 10402, 10751],
        id: 446893,
        original_language: "en",
        original_title: "Trolls World Tour",
        overview: "Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.",
        popularity: 233.655,
        poster_path: "/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg",
        release_date: "2020-03-12",
        title: "Trolls World Tour",
        video: false,
        vote_average: 7.7,
        vote_count: 122,
      },
      {
        adult: false,
        backdrop_path: "/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
        genre_ids:[28, 35, 878, 10751],
        id: 454626,
        original_language: "en",
        original_title: "Sonic the Hedgehog",
        overview: "Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.",
        popularity: 224.277,
        poster_path: "/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
        release_date: "2020-02-12",
        title: "Sonic the Hedgehog",
        video: false,
        vote_average: 7.5,
        vote_count: 2607,
      },
      {
        adult: false,
        backdrop_path: "/99QDSTfr9bOqv1kbn8YRlynbgU.jpg",
        genre_ids:[28, 12, 878],
        id: 181812,
        original_language: "en",
        original_title: "Star Wars: The Rise of Skywalker",
        overview: "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
        popularity: 207.911,
        poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
        release_date: "2019-12-18",
        title: "Star Wars: The Rise of Skywalker",
        video: false,
        vote_average: 6.5,
        vote_count: 3946,
      },
      {
        adult: false,
        backdrop_path: "/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg",
        genre_ids:[28, 878],
        id: 338762,
        original_language: "en",
        original_title: "Bloodshot",
        overview: "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
        popularity: 185.731,
        poster_path: "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
        release_date: "2020-03-05",
        title: "Bloodshot",
        video: false,
        vote_average: 7.2,
        vote_count: 1592,
      },
      {
        adult: false,
        backdrop_path: "/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg",
        genre_ids: [28, 35, 80],
        id: 495764,
        original_language: "en",
        original_title: "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
        overview: "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
        popularity: 189.735,
        poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
        release_date: "2020-02-05",
        title: "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
        video: false,
        vote_average: 7.2,
        vote_count: 2910,
      },
      {
        adult: false,
        backdrop_path: "/5mFcjZ58f9Pqg5RNv493XlfgzIX.jpg",
        genre_ids: [12, 16, 35, 10751],
        id: 412117,
        original_language: "en",
        original_title: "The Secret Life of Pets 2",
        overview: "Max the terrier must cope with some major life changes when his owner gets married and has a baby. When the family takes a trip to the countryside, nervous Max has numerous run-ins with canine-intolerant cows, hostile foxes and a scary turkey. Luckily for Max, he soon catches a break when he meets Rooster, a gruff farm dog who tries to cure the lovable pooch of his neuroses.",
        popularity: 119.685,
        poster_path: "/nYcaCNkB4EgVyvrXxxbklefDrGL.jpg",
        release_date: "2019-05-24",
        title: "The Secret Life of Pets 2",
        video: false,
        vote_average: 6.8,
        vote_count: 1343,
      },
      {
        adult: false,
        backdrop_path: "/6l3neUmnMyf2Vu8BAAEVI1dTrBd.jpg",
        genre_ids: [27, 53, 10752],
        id: 20850,
        original_language: "en",
        original_title: "Ilsa: She Wolf of the SS",
        overview: "Ilsa is a warden at a Nazi death camp that conducts experiments on prisoners. Ilsa's goal is to prove that woman can withstand more pain and suffering than men and should be allowed to fight on the front lines",
        popularity: 251.747,
        poster_path: "/kSB8msWxpqE4YENeKZJqd4CMdWd.jpg",
        release_date: "1975-10-01",
        title: "Ilsa: She Wolf of the SS",
        video: false,
        vote_average: 5,
        vote_count: 90,
      },
      {
        adult: false,
        backdrop_path: "/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg",
        genre_ids: [28, 35, 80],
        id: 522627,
        original_language: "en",
        original_title: "The Gentlemen",
        overview: "American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
        popularity: 140.278,
        poster_path: "/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg",
        release_date: "2020-01-01",
        title: "The Gentlemen",
        video: false,
        vote_average: 7.8,
        vote_count: 842,
      },
      {
        adult: false,
        backdrop_path: "/fDD0GhdsuX27yjsXO8bCzrv3Gps.jpg",
        genre_ids: [12, 35, 14, 9648, 10751],
        id: 550440,
        original_language: "en",
        original_title: "Timmy Failure: Mistakes Were Made",
        overview: "An 11-year old boy believes that he is the best detective in town and runs the agency Total Failures with his best friend, an imaginary 1,200 pound polar bear.",
        popularity: 203.508,
        poster_path: "/9Ic99kyJewgPHwl4JftJSwzUmtD.jpg",
        release_date: "2020-01-23",
        title: "Timmy Failure: Mistakes Were Made",
        video: false,
        vote_average: 6,
        vote_count: 35,
      },
      {
        adult: false,
        backdrop_path: "/oLma4sWjqlXVr0E3jpaXQCytuG9.jpg",
        genre_ids: [12, 35, 14],
        id: 512200,
        original_language: "en",
        original_title: "Jumanji: The Next Level",
        overview: "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
        popularity: 137.361,
        poster_path: "/bB42KDdfWkOvmzmYkmK58ZlCa9P.jpg",
        release_date: "2019-12-04",
        title: "Jumanji: The Next Level",
        video: false,
        vote_average: 6.9,
        vote_count: 3139,
      },
      {
        adult: false,
        backdrop_path: "/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg",
        genre_ids: [80, 18, 53],
        id: 475557,
        original_language: "en",
        original_title: "Joker",
        overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
        popularity: 115.085,
        poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        release_date: "2019-10-02",
        title: "Joker",
        video: false,
        vote_average: 8.2,
        vote_count: 11331,
      },
      {
        adult: false,
        backdrop_path: "/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg",
        genre_ids: [27, 878, 53],
        id: 570670,
        original_language: "en",
        original_title: "The Invisible Man",
        overview: "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
        popularity: 114.374,
        poster_path: "/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
        release_date: "2020-02-26",
        title: "The Invisible Man",
        video: false,
        vote_average: 7.2,
        vote_count: 1427,
      },
      {
        adult: false,
        backdrop_path: "/3tkDMNfM2YuIAJlvGO6rfIzAnfG.jpg",
        genre_ids:[18, 878],
        id: 619264,
        original_language: "es",
        original_title: "El hoyo",
        overview: "A mysterious place, an indescribable prison, a deep hole. An unknown number of levels. Two inmates living on each level. A descending platform containing food for all of them. An inhuman fight for survival, but also an opportunity for solidarity…",
        popularity: 121.635,
        poster_path: "/8ZX18L5m6rH5viSYpRnTSbb9eXh.jpg",
        release_date: "2019-11-08",
        title: "The Platform",
        video: false,
        vote_average: 7.1,
        vote_count: 2274,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 614375,
        original_language: "tl",
        original_title: "F#*@BOIS",
        overview: "Ace, 23, and Miko, 17, desperately want to become famous actors but it seems the Universe has a different plan for their lives.",
        popularity: 126.554,
        poster_path: "/hjOX3eTRR37WdsTMXOcD0gF9BA7.jpg",
        release_date: "2019-08-02",
        title: "F#*@BOIS",
        video: false,
        vote_average: 7.9,
        vote_count: 6,
      },
      {
        adult: false,
        backdrop_path: "/fDnrBn9j3hmgqOa59yWILJTZiqq.jpg",
        genre_ids: [28, 12, 35, 18, 14, 53, 10749],
        id: 14207,
        original_language: "en",
        original_title: "The Librarian: Quest for the Spear",
        overview: "When a magical artifact is lifted from his library, a meek librarian sets out to ensure its safe return.",
        popularity: 76.19,
        poster_path: "/hGF0kp0nJqmcQzywSCjkt6eykE4.jpg",
        release_date: "2004-12-05",
        title: "The Librarian: Quest for the Spear",
        video: false,
        vote_average: 6.2,
        vote_count: 354,
      },
      {
        adult: false,
        backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
        genre_ids:[35, 18, 53],
        id: 496243,
        original_language: "ko",
        original_title: "기생충",
        overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        popularity: 112.957,
        poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        release_date: "2019-05-30",
        title: "Parasite",
        video: false,
        vote_average: 8.5,
        vote_count: 6309,
      },
      {
        adult: false,
        backdrop_path: "/1uHTuwx5h9T3XzsXijMMKybDFvZ.jpg",
        genre_ids: [35, 10751, 12, 80],
        id: 772,
        original_language: "en",
        original_title: "Home Alone 2: Lost in New York",
        overview: "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas eve.",
        popularity: 74.442,
        poster_path: "/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg",
        release_date: "1992-11-19",
        title: "Home Alone 2: Lost in New York",
        video: false,
        vote_average: 6.6,
        vote_count: 5887,
      },
      {
        adult: false,
        backdrop_path: "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
        genre_ids: [12, 16, 35, 14, 10751],
        id: 508439,
        original_language: "en",
        original_title: "Onward",
        overview: "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
        popularity: 103.211,
        poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
        release_date: "2020-02-29",
        title: "Onward",
        video: false,
        vote_average: 8,
        vote_count: 1152,
      }
    ]
  }
